// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoTranslateWord": boolean;
      "autoTranslateParagraph": boolean;
      "dictionaryPaths": string;
      "dictionaryConfigs": string;
      "apiProfiles": string;
      "selectedApiProfileId": string;
      "openaiEndpoint": string;
      "openaiApiKey": string;
      "openaiModel": string;
      "openaiTemperature": string;
      "targetLanguage": string;
      "openaiPrompt": string;
    };
  }
}
